# action.yml
name: 'kubectl-alpine'
description: 'Use kubectl to speak with your cluster'
branding:
  icon: 'archive'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    VERSION: v1.19.2