on: [push]

jobs:
  test_version:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing kubectl
        id: test
        uses: ./
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}